# Generated by Django 2.1.1 on 2019-04-16 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=30, verbose_name='密码')),
                ('wechat_remark_name', models.CharField(max_length=30, verbose_name='微信备注名')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('is_activate', models.BooleanField(default=True, verbose_name='激活')),
            ],
            options={
                'verbose_name': '鲜果儿们',
                'verbose_name_plural': '鲜果儿们',
            },
        ),
        migrations.CreateModel(
            name='Remind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=30, verbose_name='事件名称')),
                ('reminder_time', models.DateTimeField(verbose_name='提醒时间')),
                ('repeat', models.CharField(choices=[('no', '无'), ('daily', '每天'), ('weekly', '每周')], default='no', max_length=10, verbose_name='周期')),
                ('fruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remind.Fruiter')),
            ],
            options={
                'verbose_name': '提醒',
                'verbose_name_plural': '提醒',
            },
        ),
        migrations.CreateModel(
            name='TomatoBell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tomato_name', models.CharField(max_length=30, verbose_name='番茄名')),
                ('amount', models.IntegerField(verbose_name='个数')),
                ('minutes', models.IntegerField(verbose_name='分钟 / 单个番茄')),
                ('turn_on', models.BooleanField(default=True, verbose_name='启用')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='设置日期')),
                ('fruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remind.Fruiter')),
            ],
            options={
                'verbose_name': '番茄钟',
                'verbose_name_plural': '番茄钟',
            },
        ),
        migrations.CreateModel(
            name='WechatCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wechat_name', models.CharField(max_length=30, verbose_name='微信昵称')),
                ('code', models.CharField(max_length=10, verbose_name='验证码')),
                ('expire_time', models.DateTimeField(verbose_name='过期时间')),
                ('is_validate', models.BooleanField(default=False, verbose_name='验证')),
            ],
            options={
                'verbose_name': '微信验证码',
                'verbose_name_plural': '微信验证码',
            },
        ),
    ]
