# Generated by Django 2.1.1 on 2019-04-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remind', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tomatobell',
            name='update_time',
        ),
        migrations.AddField(
            model_name='tomatobell',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建日期'),
        ),
    ]
