# Generated by Django 2.1.1 on 2019-04-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remind', '0003_auto_20190418_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remind',
            name='event',
            field=models.CharField(max_length=23, verbose_name='事件名称'),
        ),
    ]
